FROM python:3.14-alpine@sha256:26730869004e2b9c4b9ad09cab8625e81d256d1ce97e72df5520e806b1709f92

ENV PYTHONDONTWRITEBYTECODE=1

EXPOSE 8080
ENTRYPOINT [ "vdoc" ]
CMD ["run"]

RUN --mount=type=bind,source=./dist/,target=/pip-packages/ \
    pip install \
    --no-cache-dir \
    --no-compile \
    --upgrade \
    /pip-packages/*.whl
