FROM python:3.14-alpine@sha256:c6ead215bfd31f1e433d968853b7a769989117115b728874824e6c0a27cb96fc

ENV PYTHONDONTWRITEBYTECODE=1

EXPOSE 8080
ENTRYPOINT [ "vdoc" ]
CMD ["run"]

RUN --mount=type=bind,source=./dist/,target=/pip-packages/ \
    pip install \
    --no-cache-dir \
    --no-compile \
    --upgrade \
    /pip-packages/*.whl
