FROM python:3.14-alpine@sha256:9e9fde4d32eedce0b661d9ab91e826b62dddf28e928c230ec55f1866cac66b01

ENV PYTHONDONTWRITEBYTECODE=1

EXPOSE 8080
ENTRYPOINT [ "vdoc" ]
CMD ["run"]

RUN --mount=type=bind,source=./dist/,target=/pip-packages/ \
    pip install \
    --no-cache-dir \
    --no-compile \
    --upgrade \
    /pip-packages/*.whl
