/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProjectNameIndexImport } from './routes/$projectName/index'
import { Route as ProjectNameVersionSplatImport } from './routes/$projectName/$version.$'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProjectNameIndexRoute = ProjectNameIndexImport.update({
  id: '/$projectName/',
  path: '/$projectName/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectNameVersionSplatRoute = ProjectNameVersionSplatImport.update({
  id: '/$projectName/$version/$',
  path: '/$projectName/$version/$',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$projectName/': {
      id: '/$projectName/'
      path: '/$projectName'
      fullPath: '/$projectName'
      preLoaderRoute: typeof ProjectNameIndexImport
      parentRoute: typeof rootRoute
    }
    '/$projectName/$version/$': {
      id: '/$projectName/$version/$'
      path: '/$projectName/$version/$'
      fullPath: '/$projectName/$version/$'
      preLoaderRoute: typeof ProjectNameVersionSplatImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$projectName': typeof ProjectNameIndexRoute
  '/$projectName/$version/$': typeof ProjectNameVersionSplatRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$projectName': typeof ProjectNameIndexRoute
  '/$projectName/$version/$': typeof ProjectNameVersionSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/$projectName/': typeof ProjectNameIndexRoute
  '/$projectName/$version/$': typeof ProjectNameVersionSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$projectName' | '/$projectName/$version/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$projectName' | '/$projectName/$version/$'
  id: '__root__' | '/' | '/$projectName/' | '/$projectName/$version/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProjectNameIndexRoute: typeof ProjectNameIndexRoute
  ProjectNameVersionSplatRoute: typeof ProjectNameVersionSplatRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProjectNameIndexRoute: ProjectNameIndexRoute,
  ProjectNameVersionSplatRoute: ProjectNameVersionSplatRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$projectName/",
        "/$projectName/$version/$"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$projectName/": {
      "filePath": "$projectName/index.tsx"
    },
    "/$projectName/$version/$": {
      "filePath": "$projectName/$version.$.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
