name: Setup JFrog CLI
description: Configure JFrog CLI with OIDC authentication

runs:
  using: composite
  steps:
    - uses: jfrog/setup-jfrog-cli@deda456d982fc5e9a7a020b63eb0d2968aedd33e # v5
      env:
        JF_URL: https://voraus.jfrog.io
      with:
        oidc-provider-name: voraus-github-organization
        disable-auto-build-publish: "true"
