"""Let one project be featured

Revision ID: e612a95748e2
Revises: 4a76c9366f5c
Create Date: 2026-10-01 15:41:51.790886
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e612a95748e2"
down_revision: str | Sequence[str] | None = "4a76c9366f5c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades the schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("featured", sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column("featured_label", sa.String(), nullable=True))
        batch_op.create_index(
            "uq_project_featured",
            ["featured"],
            unique=True,
            sqlite_where=sa.text("featured"),
            postgresql_where=sa.text("featured"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades the schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_project_featured", sqlite_where=sa.text("featured"), postgresql_where=sa.text("featured")
        )
        batch_op.drop_column("featured_label")
        batch_op.drop_column("featured")

    # ### end Alembic commands ###
