"""Create the project, version and category tables

Revision ID: 4a76c9366f5c
Revises:
Create Date: 2026-09-29 15:14:27.902873
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4a76c9366f5c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades the schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
        sa.UniqueConstraint("name", name=op.f("uq_category_name")),
    )
    op.create_table(
        "project",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum("listed", "unlisted", "locked", name="projectvisibility", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["category.id"], name=op.f("fk_project_category_id_category"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_project")),
    )
    op.create_table(
        "version",
        sa.Column("project_name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_name"], ["project.name"], name=op.f("fk_version_project_name_project"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_name", "version", name=op.f("pk_version")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades the schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("version")
    op.drop_table("project")
    op.drop_table("category")
    # ### end Alembic commands ###
