name: CI pipeline

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - "main"
    tags:
      - '*'

jobs:
  tests-and-coverage:
    uses: ./.github/workflows/tests_and_coverage.yml
  linting:
    uses: ./.github/workflows/linting.yml
  build:
    uses: ./.github/workflows/build.yml
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/')
    needs:
      - tests-and-coverage
      - linting
      - build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Publish project
        run: |
          echo "Publishing project..."

